Repository techeer-f5/jmt-monster-backend, pull requests merged in 2022-07, with the labels that each got.

#78 이사 API 테스트 작성
  src/main/java/com/techeer/f5/jmtmonster/domain/home/domain/Home.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/mapper/HomeMapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/mapper/HomeMapperImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/repository/HomeQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/service/HomeService.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/domain/User.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/service/UserService.java
  src/test/java/com/techeer/f5/jmtmonster/domain/home/controller/HomeControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/home/mapper/HomeMapperTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/home/repository/HomeRepositoryTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/home/service/HomeServiceTest.java
Labels: enhancement

#85 리뷰 도메인 N+1 쿼리 해결
  .idea/codeStyles/codeStyleConfig.xml
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dao/ReviewQueryRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dao/ReviewQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dao/ReviewRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/Review.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewFood.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewImage.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewService.java
  src/test/java/com/techeer/f5/jmtmonster/domain/review/dao/ReviewRepositoryTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewServiceTest.java
Labels: troubleshooting

#89 AWS API 키 주입 없는 S3Manager 테스트
  src/main/java/com/techeer/f5/jmtmonster/domain/review/service/S3Service.java
  src/main/java/com/techeer/f5/jmtmonster/s3/util/S3Manager.java
  src/main/resources/application-test.yml
  src/test/java/com/techeer/f5/jmtmonster/s3/S3ManagerTest.java
Labels: enhancement

#87 사용자 프로필 API 추가
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRequestQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/controller/UserProfileController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/repository/UserQueryRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/repository/UserQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/repository/UserRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/service/UserService.java
  src/main/resources/static/docs/openapi3.json
  src/test/java/com/techeer/f5/jmtmonster/domain/user/controller/UserProfileControllerTest.java
Labels: bug, enhancement

#91 Review, User 테스트 깨지는 것 수정
  src/main/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewService.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/domain/User.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/repository/UserRepository.java
  src/test/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewServiceTest.java
Labels: troubleshooting

#92 User 엔티티 내 주소 관련 컬럼 제거
  src/main/java/com/techeer/f5/jmtmonster/domain/home/repository/HomeQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/domain/User.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/dto/UserMapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/service/UserService.java
  src/test/java/com/techeer/f5/jmtmonster/domain/home/repository/HomeRepositoryTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/home/service/HomeServiceTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/user/UserControllerTest.java
Labels: enhancement

#94 ID로 사용자 프로필 조회 API 추가
  src/main/java/com/techeer/f5/jmtmonster/domain/user/controller/UserProfileController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/service/UserService.java
Labels: enhancement

#93 AuthOnly 어노테이션 작성, AOP로 인증 핸들링
  src/main/java/com/techeer/f5/jmtmonster/domain/home/controller/HomeController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/aop/annotation/AuthOnly.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/aop/aspect/AuthAspect.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dao/ReviewQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/controller/UserController.java
  src/test/java/com/techeer/f5/jmtmonster/domain/user/UserControllerTest.java
Labels: enhancement
