Repository techeer-f5/jmt-monster-backend, pull requests merged in 2022-06, with the labels that each got.

#65 Entity 생성 후 저장시 저장 전후 ID(기본키) 값이 다른 이슈
  src/test/java/com/techeer/f5/jmtmonster/domain/UuidIdTest.java
Labels: bug

#68 S3 API 테스트 코드 완성
  build.gradle
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/mapper/S3Mapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/controller/S3Controller.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dto/response/S3DeleteResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dto/response/S3UploadResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/service/S3Service.java
  src/main/java/com/techeer/f5/jmtmonster/s3/util/S3Manager.java
  src/test/java/com/techeer/f5/jmtmonster/domain/review/controller/S3ControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/review/service/S3ServiceTest.java
  src/test/java/com/techeer/f5/jmtmonster/s3/S3ManagerTest.java
  src/test/java/com/techeer/f5/jmtmonster/s3/S3MockConfig.java
Labels: implementation

#66 놀러가기 기능
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/controller/FriendController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendQueryRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/domain/Friend.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/domain/FriendRequest.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/mapper/FriendMapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/request/FriendHangOutDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/request/FriendUpdateRequestDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/service/FriendService.java
  src/main/resources/static/docs/openapi3.json
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/controller/FriendControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/controller/FriendRequestControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendQueryRepositoryTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/service/FriendServiceTest.java
  src/test/java/com/techeer/f5/jmtmonster/util/FieldUtil.java
Labels: enhancement

#71 TokenValidationResponseDto에 is 접두사 붙이기
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/controller/TokenValidationController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/dto/TokenValidationResponseDto.java
Labels: bug

#74 놀러가기 상태 삭제
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/controller/FriendController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendQueryRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/domain/Friend.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/mapper/FriendMapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/request/FriendHangOutDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/response/FriendResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/service/FriendService.java
  src/main/resources/static/docs/openapi3.json
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/controller/FriendControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendQueryRepositoryTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/service/FriendServiceTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/review/controller/S3ControllerTest.java
Labels: enhancement

#69 temporarily Merge for Domain "Restaurant"
  src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
Labels: proof-of-concept

#73 이사 API 작성
  build.gradle
  src/main/java/com/techeer/f5/jmtmonster/domain/home/controller/HomeController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/domain/Home.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/domain/HomeToUser.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/dto/HomeHistoriesDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/dto/HomeHistoryDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/dto/HomeRequestDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/dto/HomeResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/mapper/HomeMapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/mapper/HomeMapperImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/repository/HomeQueryRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/repository/HomeQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/repository/HomeRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/repository/HomeToUserRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/home/service/HomeService.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/domain/User.java
Labels: enhancement
