Repository techeer-f5/jmt-monster-backend, pull requests merged in 2022-04, with the labels that each got.

#10 Spring 설정 추가
  build.gradle
  src/main/java/com/techeer/f5/jmtmonster/global/config/SecurityConfig.java
  src/main/resources/META-INF/spring-configuration-metadata.json
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#13 Google 코딩 스타일 적용
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
Labels: enhancement

#14 Exception Handler 추가
  src/main/java/com/techeer/f5/jmtmonster/domain/hello/controller/HelloController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/hello/dto/HelloRequestDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/hello/dto/HelloResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/ErrorResponse.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/GlobalExceptionHandler.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/exception/CustomStatusException.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/exception/ErrorCode.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/exception/ResourceNotFoundException.java
Labels: enhancement

#16 카카오 소셜 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/config/KakaoConfig.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/controller/KakaoCallbackController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/controller/KakaoLoginController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/domain/AuthProvider.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/domain/PersistentToken.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/dto/KakaoOAuthResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/dto/KakaoUserDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/dto/PersistentTokenDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/repository/PersistentTokenRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/service/KakaoCallbackService.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/service/KakaoLoginService.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/domain/AuthProvider.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/domain/User.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/repository/UserRepository.java
  src/main/java/com/techeer/f5/jmtmonster/global/config/RestTemplateConfig.java
  src/main/resources/application-secret.template.yml
  src/main/resources/application.yml
Labels: enhancement

#21 README.md에 기술 스택 추가
  README.md
Labels: documentation

#26 Jackson LocalDateTime 매핑 해결, 카멜 케이스 변환, Spring REST Docs & Swagger 연동
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/domain/PersistentToken.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/domain/User.java
  src/main/java/com/techeer/f5/jmtmonster/global/config/RestTemplateConfig.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/static/docs/openapi3.json
  src/test/java/com/techeer/f5/jmtmonster/domain/hello/HelloControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/global/ApplicationTests.java
Labels: documentation, enhancement, troubleshooting

#28 토큰 핸들링 인터셉터 작성
  src/main/java/com/techeer/f5/jmtmonster/security/config/BearerTokenConfig.java
  src/main/java/com/techeer/f5/jmtmonster/security/extractor/AuthorizationExtractor.java
  src/main/java/com/techeer/f5/jmtmonster/security/extractor/HeaderExtractor.java
  src/main/java/com/techeer/f5/jmtmonster/security/interceptor/BearerTokenInterceptor.java
Labels: enhancement, implementation

#29 토큰 유효성 검증 API 작성
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/controller/TokenValidationController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/dto/TokenValidationResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/service/TokenValidationService.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/Dto/UserDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/domain/User.java
Labels: enhancement, implementation

#31 CSRF 해제, 카카오 API 프론트에서 잘 동작하게 리팩토링
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/config/KakaoConfig.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/controller/TokenValidationController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/service/KakaoCallbackService.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/controller/UserController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/service/UserService.java
  src/main/java/com/techeer/f5/jmtmonster/global/config/JacksonConfig.java
  src/main/java/com/techeer/f5/jmtmonster/global/config/RestTemplateConfig.java
  src/main/java/com/techeer/f5/jmtmonster/global/config/SecurityConfig.java
  src/main/java/com/techeer/f5/jmtmonster/security/config/BearerTokenConfig.java
  src/main/java/com/techeer/f5/jmtmonster/security/extractor/AuthorizationExtractor.java
  src/main/java/com/techeer/f5/jmtmonster/security/interceptor/BearerTokenInterceptor.java
Labels: enhancement, refactor, implementation

#33 Github Actions 이미지 빌드 & AWS ECR 연동
  .github/workflows/build-image.yml
  .gitignore
  build.gradle
Labels: enhancement, system-design

#32 친구 API
  build.gradle
  src/main/java/com/techeer/f5/jmtmonster/Application.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/controller/FriendRequestController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRequestRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/domain/FriendRequest.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/domain/FriendRequestStatus.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/domain/FriendRequestStatusConverter.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/mapper/FriendRequestMapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/request/FriendRequestCreateRequestDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/request/FriendRequestCreateServiceDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/request/FriendRequestModel.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/request/FriendRequestUpdateRequestDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/request/FriendRequestUpdateServiceDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/response/FriendRequestResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/service/FriendRequestService.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/dto/BasicUserResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/dto/UserMapper.java
  src/main/java/com/techeer/f5/jmtmonster/global/domain/domain/BaseTimeEntity.java
  src/main/java/com/techeer/f5/jmtmonster/global/domain/dto/BaseTimeEntityDto.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/ErrorResponse.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/GlobalExceptionHandler.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/exception/CustomStatusErrorsException.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/exception/DuplicateResourceException.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/exception/ErrorCode.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/exception/FieldErrorWrapper.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/exception/InnerResourceNotFoundException.java
Labels: enhancement
