Repository techeer-f5/jmt-monster-backend, pull requests merged in 2022-05, with the labels that each got.

#40 사용자 추가 정보 입력 API 작성
  build.gradle
  src/main/java/com/techeer/f5/jmtmonster/domain/oauth/controller/TokenValidationController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/controller/UserController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/domain/User.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/dto/ExtraUserInfoRequestDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/dto/UserDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/dto/UserMapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/dto/UserResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/repository/UserRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/service/UserService.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/exception/ErrorCode.java
  src/main/java/com/techeer/f5/jmtmonster/global/error/exception/NotAuthorizedException.java
  src/main/java/com/techeer/f5/jmtmonster/global/utils/JsonMapper.java
  src/main/java/com/techeer/f5/jmtmonster/security/interceptor/BearerTokenInterceptor.java
  src/main/resources/application.yml
  src/main/resources/static/docs/openapi3.json
  src/test/java/com/techeer/f5/jmtmonster/domain/hello/HelloControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/user/UserControllerTest.java
Labels: enhancement

#46 사용자 추가 정보 업데이트
  src/main/java/com/techeer/f5/jmtmonster/domain/user/controller/UserController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/domain/User.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/service/UserService.java
Labels: enhancement

#35 리뷰 API
  .gitignore
  build.gradle
  src/main/java/com/techeer/f5/jmtmonster/domain/review/controller/ReviewRequestController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dao/ReviewFoodRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dao/ReviewImageRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dao/ReviewRequestRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/Like.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewFood.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewImage.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewRequest.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/Star.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dto/mapper/ReviewRequestMapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dto/request/ReviewRequestCreateRequestDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dto/request/ReviewRequestCreateServiceDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dto/request/ReviewRequestModel.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dto/request/ReviewRequestUpdateRequestDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dto/request/ReviewRequestUpdateServiceDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/dto/response/ReviewRequestResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestService.java
  src/main/java/com/techeer/f5/jmtmonster/s3/config/AmazonS3Config.java
  src/main/java/com/techeer/f5/jmtmonster/s3/util/S3Uploader.java
  src/main/resources/application-secret.yml
  src/main/resources/application.yml
Labels: enhancement, proof-of-concept

#45 음식점 도메인 추가
  src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/mapper/RestaurantMapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/request/RestaurantRequestDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/response/RestaurantResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/entity/Restaurant.java
  src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/RestaurantService.java
Labels: proof-of-concept

#48 테스트 프로필 관련 오류 수정
  build.gradle
  src/main/java/com/techeer/f5/jmtmonster/domain/user/repository/UserRepository.java
  src/main/resources/application-test.yml
  src/main/resources/static/docs/openapi3.json
  src/test/java/com/techeer/f5/jmtmonster/domain/hello/HelloControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/user/UserControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/global/ApplicationTests.java
Labels: troubleshooting

#52 친구 요청 API 쿼리 성능 개선
  build.gradle
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRequestCustomRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRequestCustomRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRequestRepository.java
  src/main/java/com/techeer/f5/jmtmonster/global/config/QuerydslConfig.java
  src/main/resources/application.yml
Labels: enhancement

#54 feat: add MenuService
  src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
Labels: enhancement

#56 친구 API 테스트 추가 및 기존 테스트 작동하도록 수정
  src/main/java/com/techeer/f5/jmtmonster/Application.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/controller/FriendController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/controller/FriendRequestController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendQueryRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRequestCustomRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRequestQueryRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRequestQueryRepositoryImpl.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRequestRepository.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/mapper/FriendMapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/request/FriendUpdateRequestDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/request/FriendUpdateServiceDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/dto/response/FriendResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/friend/service/FriendService.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/controller/UserController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/domain/User.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/dto/UserMapper.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/dto/UserResponseDto.java
  src/main/java/com/techeer/f5/jmtmonster/domain/user/service/UserService.java
  src/main/java/com/techeer/f5/jmtmonster/global/config/JacksonConfig.java
  src/main/java/com/techeer/f5/jmtmonster/global/config/JpaAuditingConfig.java
  src/main/java/com/techeer/f5/jmtmonster/global/config/RestTemplateConfig.java
  src/main/java/com/techeer/f5/jmtmonster/global/utils/JsonMapper.java
  src/main/java/com/techeer/f5/jmtmonster/global/utils/ObjectMapperFactory.java
  src/main/java/com/techeer/f5/jmtmonster/security/config/BearerTokenConfig.java
  src/main/resources/static/docs/openapi3.json
  src/test/java/com/techeer/f5/jmtmonster/document/util/ResponseFieldDescriptorUtils.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/FriendControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/controller/FriendControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/controller/FriendRequestControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/controller/FriendRequestControllerTests.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendQueryRepositoryTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/dao/FriendRequestQueryRepositoryTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/friend/service/FriendServiceTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/hello/HelloControllerTest.java
  src/test/java/com/techeer/f5/jmtmonster/domain/user/UserControllerTest.java
Labels: bug, enhancement, refactor

#60 Feat/add review api
  build.gradle
  src/main/java/com/techeer/f5/jmtmonster/domain/review/controller/ReviewRequestController.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/controller/S3Controller.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestService.java
  src/main/java/com/techeer/f5/jmtmonster/domain/review/service/S3Service.java
  src/main/java/com/techeer/f5/jmtmonster/s3/util/S3Manager.java
Labels: implementation
